#!/bin/bash

# Kill old sessions
_kill_procs() {
kill -TERM $chrome
wait $chrome
kill -TERM $xvfb
}
# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

# Start Xvfb
XVFB_WHD=${XVFB_WHD:-1280x720x16}
Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

# Start chrome
#/opt/google/chrome/google-chrome-base --no-sandbox $@ &
/usr/bin/chromium --no-sandbox $@ &
chrome=$!

wait $chrome
wait $xvfb
